"""Remove title column from Post table

Revision ID: 1ccf85d09951
Revises: 8e41fbdda2ab
Create Date: 2025-12-12 16:45:23.175470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccf85d09951'
down_revision = '8e41fbdda2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
