"""Make overall rating computed from other ratings

Revision ID: 2b1e6e998022
Revises: 37f13adb8eeb
Create Date: 2025-11-29 12:00:27.340474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1e6e998022'
down_revision = '37f13adb8eeb'
branch_labels = None
depends_on = None


def upgrade():
    # Update existing posts to have computed ratings
    op.execute("""
        UPDATE post SET rating = ROUND(
            (rating_professor + rating_material + rating_workload + rating_peers) / 4.0
        ) 
        WHERE rating_professor IS NOT NULL 
        AND rating_material IS NOT NULL 
        AND rating_workload IS NOT NULL 
        AND rating_peers IS NOT NULL
    """)
    
    # Make rating column nullable since it's now computed
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('rating', existing_type=sa.Integer(), nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('rating', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###
