"""add index post course_id

Revision ID: 8b520adcb356
Revises: 3bcc10f50651
Create Date: 2025-12-04 14:21:42.600974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b520adcb356'
down_revision = '3bcc10f50651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_course_id'))

    # ### end Alembic commands ###
